<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\SyncServerWinForms\bin\Debug\netcoreapp3.1\Newtonsoft.Json.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>